# Site settings
title: pascal.poizat
author: Pascal Poizat
email: firstname.lastname@gmail.com
email1: firstname.lastname@u-paris10.fr
email2: firstname.lastname@lip6.fr
description: > # this means to ignore newlines until "baseurl:"
  Full Professor at Université Paris Ouest<br/>
  LIP6 UMR 7606 CNRS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pascalpoizat.github.io" # the base hostname & protocol for your site
twitter_username: pascalpoizat
github_username:  pascalpoizat

# Build settings
markdown: kramdown
highlighter: pygments # rouge is not supported by GitHub

# Gems
# gems: [rouge] # rouge is not supported by GitHub
