# Site settings
title: pascal.poizat
author: Pascal Poizat
email: firstname.lastname@gmail.com
email1: firstname.lastname@u-paris10.fr
email2: firstname.lastname@lip6.fr
description: > # this means to ignore newlines until "baseurl:"
  Full Professor at Université Paris Ouest<br/>
  LIP6 UMR 7606 CNRS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pascalpoizat.github.io" # the base hostname & protocol for your site
twitter_username: pascalpoizat
github_username:  pascalpoizat

exclude:  ['Gemfile*', '*.sh', 'update_site.sh']

# Build settings
markdown: kramdown

highlighter: pygments
gems: ['jekyll/scholar']

scholar:
  style: _bibliography/mystyle.csl
  locale: en
  sort_by: year, month
  order: descending
  group_by: none
  group_order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  use_raw_bibtex_entry: true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"