#
# SITE SETTINGS
#

# site information

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pascalpoizat.github.io" # the base hostname & protocol for your site

# author information

title: pascal.poizat
author: Pascal Poizat
picture: images/poizat_2015b.jpg
email: firstname.lastname@gmail.com
email1: firstname.lastname@u-paris10.fr
email2: firstname.lastname@lip6.fr
description: > # this means to ignore newlines until the next tag
  Professor at Université Paris Ouest<br/>
  LIP6 UMR 7606 CNRS
twitter_username: pascalpoizat
github_username:  pascalpoizat
dblp:
  site: http://www.informatik.uni-trier.de/~ley/pers/hd
  user: p/Poizat:Pascal

# apparence of buttons

link_btn_size: btn-xs
link_btn_color: btn-primary

# bibliography

kind:
  label: pp_kind # label used in .bib files to denote the kind (international/national) of references
  separate:  # should international/national references be separated: (true | false)
    article: true
    inbook: false
    inproceedings: true

#
# YOU SHOULD AVOID DOING MODIFICATION BELOW THIS POINT
#

# Build settings

exclude:  ['Gemfile*', '*.sh', 'update_site.sh']

gems: ['jekyll/scholar']

markdown: kramdown
highlighter: rouge

kramdown:
     # input: GFM
     syntax_highlighter: rouge

scholar:
  style: _bibliography/mystyle.csl
  locale: en
  sort_by: year, month
  order: descending
  group_by: none
  group_order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  use_raw_bibtex_entry: true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"